### ISSUE TITLE
hi, jut found about this and it is wonderful. Can you help me with how to get the report in any specific location of my project folder. By default it is picking up a location where my test files resides. The way we can set the Pytest normal HTML report with the argument like --html=[Folder location}, same, can we do it for this report generation.

### ISSUE THREAD

**Issue by ghost** [adiralashiva8/pytest-metrics#6] opened 2020-06-03 08:09 UTC

**Comment by adiralashiva8** [comment] 2020-06-03 08:14
Duplicate of #7

**Closed as completed** 2020-06-03 08:14 UTC
Labels: duplicate
